"""
Add has_folder column to scripts

Revision ID: 20251018_add_has_folder_to_scripts
Revises: 2b39e144884e
Create Date: 2025-10-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251018_add_has_folder_to_scripts'
down_revision = '2b39e144884e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_folder', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_column('has_folder')

    # ### end Alembic commands ###
