"""Rename filename to name in Prompt model

Revision ID: 2b39e144884e
Revises: bda468c4c689
Create Date: 2025-10-17 03:30:30.529783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b39e144884e'
down_revision = 'bda468c4c689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_prompts_filename'))
        batch_op.create_index(batch_op.f('ix_prompts_name'), ['name'], unique=True)
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_prompts_name'))
        batch_op.create_index(batch_op.f('ix_prompts_filename'), ['filename'], unique=1)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
