"""Initial migration with Script and Prompt models

Revision ID: 973fcf29b850
Revises: 
Create Date: 2025-10-17 02:48:10.707829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973fcf29b850'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_filename'), ['filename'], unique=True)

    op.create_table('scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('audio_status', sa.String(length=50), nullable=True),
    sa.Column('images_status', sa.String(length=50), nullable=True),
    sa.Column('transcript_status', sa.String(length=50), nullable=True),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('scenes', sa.Text(), nullable=False),
    sa.Column('generation_params', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_filename'))

    op.drop_table('prompts')
    # ### end Alembic commands ###
